config/routes.rb
Flashcards::Application.routes.draw do
  root :to => "notebooks#index"
  resources :notebooks do
    resources :pages do
      get 'flashcards', :on => :collection
    end
  end
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  attr_accessible :title

  has_many :pages

  def tags
    tags_list = []
    self.pages.each do |page|
      tags_list += page.tags
    end
    tags_list.uniq
  end
  
  def pages_count
    Page.where(:notebook_id => self.id).count
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :notebook_id, :page_number, :title, :tag_list
  acts_as_taggable

  belongs_to :notebook

  def rendered_content
    # RDiscount.new(self.content).to_html.html_safe
    markdown.render(self.content).html_safe
  end

  def markdown
    @renderer||=Redcarpet::Markdown.new(Redcarpet::Render::HTML, fenced_code_blocks: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  def index
    @notebooks = Notebook.all
  end

  def show
    @notebook = Notebook.find params[:id]
  end

  def new
    @notebook = Notebook.new
  end

  def create
    @notebook = Notebook.create params[:notebook]
    redirect_to notebooks_path
  end

  def edit
  end

  def update
    
  end
end

app/controllers/pages_controller.rb
require 'will_paginate/array'

class PagesController < ApplicationController
  before_filter :load_notebook

  def index
    @pages = @notebook.pages.order("updated_at desc, created_at desc")
    @pages = Page.tagged_with params[:tag] if params[:tag]
  end

  def flashcards
    if params[:shuffle]
      params[:seed] = Random.new_seed
      params.delete :shuffle
    end

    Kernel.srand params[:seed].to_i
    @pages = @notebook.pages.shuffle
    @pages = Page.tagged_with(params[:tag]).shuffle if params[:tag]
    @pages = @pages.paginate(:page => params[:page], :per_page => 1)
  end

  def show
    @page = Page.find params[:id]
  end

  def new
    @page = Page.new
  end

  def create
    @page = @notebook.pages.build(params[:page]).save
    redirect_to notebook_pages_path(@notebook)
  end

  def edit
    @page = Page.find params[:id]
  end

  def update
    @page = Page.find params[:id]
    @page.update_attributes params[:page]
    redirect_to notebook_pages_path(@notebook)
  end

  def destroy
    @page = Page.find params[:id]
    @page.delete
    redirect_to notebook_pages_path(@notebook)
  end

  private
  def load_notebook
    @notebook = Notebook.find params[:notebook_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flashcards" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Flashcards</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "New notebook", new_notebook_path  %></li>
              <%= content_for :top_nav %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav hidden-phone">
            <ul class="nav nav-list">
              <%= content_for :sidebar %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <%= link_to "Uri Gorelik", "http://urigorelik.info/" %> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/notebooks/_form.html.erb
<%= form_for @notebook do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %> 
  <br>
  <%= f.submit %>
<% end %>

app/views/notebooks/_notebook.html.erb
<h4><%= link_to notebook.title, notebook_pages_path(notebook) %></h4>

app/views/notebooks/index.html.erb
<h1>Index for notebooks</h1>
<%= render @notebooks %>

app/views/notebooks/new.html.erb
<h1>New notebook</h1>

<%= render "form" %>

app/views/notebooks/show.html.erb
<%= render "notebook" %>

app/views/pages/_form.html.erb
<%= form_for [@notebook,@page] do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content, :class => "content" %>  
  <br>
  <%= f.label :tags %>
  <%= f.text_field :tag_list %>
  <br>
  <%= f.submit :class => "btn btn-success" %>

<% end %>

app/views/pages/_page.html.erb
<h3><%= page.title %></h3>

<div class="page-controls">
  <small>
    <%= link_to "d", notebook_page_path(@notebook, page), :method => :delete, :confirm => "Are you sure?" %>
    -
    <%= link_to 'e', edit_notebook_page_path(@notebook, page) %>
  </small></div>

<div class="page-content">
  <%= page.rendered_content %>
</div>

app/views/pages/edit.html.erb
<%= render "form" %>

app/views/pages/flashcards.html.erb
<%= content_for :sidebar do %>
  <li><strong><%= link_to "All", flashcards_notebook_pages_path(@notebook, :shuffle => 1) %></strong></li>
  <% @notebook.tags.sort{|a,b| a.name <=> b.name}.each do |tag| %>
    <li><%= link_to tag.name, flashcards_notebook_pages_path(@notebook, :tag => tag.name) %></li>
  <% end %>
<% end %>

<%= content_for :top_nav do %>

  <li><%= link_to @notebook.title, notebook_pages_path(@notebook) %></li>
  <li><%= link_to "New flashcard", new_notebook_page_path(@notebook) %></li>
<% end %>



<% @pages.each do |page| %>
  <h3><%= page.title %></h3>
  <p><%= link_to_function "Show!", "toggleFlashcard()", :class => "btn btn-success"  %></p>
  <div class="content flashcard" style="display:none">
    <%= page.rendered_content %>
  </div>
<% end %>

<%= will_paginate @pages %>

app/views/pages/index.html.erb
<%= content_for :sidebar do %>
  <li class="nav-header">In notebook: <%= link_to @notebook.title, notebook_pages_path(@notebook) %></li>
  <% @notebook.tags.sort{|a,b| a.name <=> b.name}.each do |tag| %>
    <li><%= link_to tag.name, notebook_pages_path(@notebook, :tag => tag.name) %></li>
  <% end %>
<% end %>

<%= content_for :top_nav do %>
  <li><%= link_to "Flashcards", flashcards_notebook_pages_path(@notebook) %></li>
  <li><%= link_to "Flashcards Shuffle", flashcards_notebook_pages_path(@notebook, :shuffle => true) %></li>
<% end %>

<h1>Pages for <%= @notebook.title %></h1>


<h2><%= link_to "New page", new_notebook_page_path(@notebook), :class => "btn btn-success" %></h2>


<% @pages.each do |page| %>
  <%= render page %>
<% end %>

app/views/pages/new.html.erb
<h1>New page for <%= @notebook.title %></h1>
<%= render "form" %>

app/views/pages/show.html.erb
<%= @page.title %>